blueprint:
  name: "Motion-Activated Light Off"
  description: "Automatically turns off lights after a specified time when no motion is detected"
  domain: automation
  input:
    motion_sensor:
      name: "Motion Sensor"
      description: "Motion sensor that detects movement in the area"
      selector:
        entity:
          domain: binary_sensor
    
    light_entity:
      name: "Light Entity"
      description: "Light or light group to control"
      selector:
        entity:
          domain: light
    
    turn_off_delay:
      name: "Turn Off Delay"
      description: "Time in minutes to wait before turning off the light after no motion is detected"
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutes"

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "off"

condition:
  - condition: state
    entity_id: !input light_entity
    state: "on"

action:
  - delay:
      minutes: !input turn_off_delay
  - condition: state
    entity_id: !input motion_sensor
    state: "off"
  - condition: state
    entity_id: !input light_entity
    state: "on"
  - service: light.turn_off
    target:
      entity_id: !input light_entity 